### ISSUE TITLE
Document pins that the MCP2515 is wired to?

### ISSUE THREAD

**Issue by pdp7** [battlesnake/beaglebone-spi0-mcp2515#1]
Hello, thank you for sharing this dts file.  I am trying to get a MCP2515 working with the BeagleBone Black on SPI0 with the 4.14.78-bone17 kernel.

Would it be possible for to document how you had the MCP2515 wired to the P8/P9 headers on the BeagleBone Black?

Also, I would be curious to know what kernel version you were using with this Device Tree Overlay.  I am trying to get this working with [u-boot overlays](https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays) as the [cape manager driver has been deprecated](https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#Where_did_the_slots_file_go.3F).

thanks!
drew

**Comment by battlesnake** [comment]
Hi,

I can't remember.  The MCP2515 board was just for demonstration purposes for a small project, I usually use the built-in CAN protocol hardware plus an external bus driver.

You can lookup the pin IDs from my dts against the addresses from the Sitara datasheet (or take the addresses from some community-produced source like [here](http://exploringbeaglebone.com/wp-content/uploads/resources/BBBP9Header.png)), then adjust the DTS or your wiring as necessary.

You can either merge this into the main DT you're booting the kernel with, or (my preferred way for prototyping) load it dynamically as an overlay at runtime via the Renesas R-car kernel patch, which provides a userspace interface for loading/unloading DT overlays.

**Comment by battlesnake** [comment]
I've not actually used a BeagleBone for some months now, I have my own custom boards for this kind of work now, in order to reduce the colossal amount of wiring and boards that I had to deal with when using BeagleBone / RPi / Arduinos.

**Comment by pdp7** [comment]
@battlesnake thank you for following up.

I'm hoping to get this MCP2515 breakout board working on the BBB SPI0 and then create a pull request on https://github.com/beagleboard/bb.org-overlays/

**Comment by pdp7** [comment]
To followup, here is a GitHub gist which shows how I was able to wire the MCP2515 to SPI0 on the BeagleBone Black and successfully observe the mcp251x
initialize it and load the can0 interface:
https://gist.github.com/pdp7/20dddbeffe83082e3c94ab0903563783

Photos of MCP2515 breakout board wired to SPI0 on the BeagleBone Black:
https://photos.app.goo.gl/1UUAHhRngzwiVWha9

add this to /boot/uEnv.txt:
```
uboot_overlay_addr0=/lib/firmware/BB-SPIDEV0-00A0.dtbo
uboot_overlay_addr1=/lib/firmware/MCP2515.dtbo
```
grab the MCP2515 overlay and install it:
```
cd /opt/source/bb.org-overlays/
wget https://github.com/battlesnake/beaglebone-spi0-mcp2515/blob/master/MCP2515.dts
sudo ./install.sh
```
After rebooting, the mcp251x driver should initialize the MCP2515 device and these commands from the Macchina documentation should work:
```
sudo ip link set can0 type can bitrate 500000 listen-only on
sudo ifconfig can0 up
```

**Comment by pdp7** [comment]
@battlesnake thanks for creating this dts. I have created pull request https://github.com/beagleboard/bb.org-overlays/pull/101
